# Generated by Django 4.2.4 on 2024-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dept', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('salary', models.IntegerField()),
                ('designation', models.TextField()),
                ('gender', models.TextField()),
                ('pan_no', models.TextField()),
                ('aadhar_no', models.IntegerField()),
                ('dateofbirth', models.TextField()),
                ('dateofjoining', models.TextField()),
                ('bankname', models.TextField()),
                ('ac_no', models.IntegerField()),
            ],
        ),
    ]
