# Generated by Django 4.2.4 on 2024-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='bankname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='pan_no',
            field=models.CharField(max_length=20),
        ),
    ]
