# Generated by Django 4.2.4 on 2024-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_database_bankname_alter_database_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='aadhar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='database',
            name='ac_no',
            field=models.BigIntegerField(),
        ),
    ]
