# Generated by Django 4.2.4 on 2024-05-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_database_aadhar_no_alter_database_ac_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='email',
        ),
        migrations.RemoveField(
            model_name='database',
            name='phone',
        ),
    ]
