# Generated by Django 4.2.4 on 2024-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_database_email_remove_database_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='uan_no',
            field=models.CharField(default=1210102, max_length=20),
            preserve_default=False,
        ),
    ]
